services:
  - type: web
    name: drss-laravel-app
    env: docker
    plan: free
    dockerContext: ./drss
    dockerfilePath: ./drss/Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: PORT
        value: '80'
